<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/VideoExport.Core/VideoExport.Core.csproj" />
    <Compile Include="../../src/VideoExport.Plugin/NativeCaptureScope.cs" Link="NativeCaptureScope.cs" />
  </ItemGroup>
</Project>
