using System.Reflection;
using AAVideoExport.Integration;
var tests = new (string,Action)[] {
("ready only after host setup",()=>{RenderControlV1.BeginHostInitialization();Check(!RenderControlV1.IsReady&&!RenderControlV1.IsRenderingOwned);Throws(()=>RenderControlV1.Acquire());RenderControlV1.CompleteHostInitialization();Check(RenderControlV1.IsReady&&RenderControlV1.ProtocolVersion==1);}),
("nested panel preparation and capture leases never transiently release",()=>{Ready();int acquire=0,release=0;RenderControlV1.BeforeAcquire+=()=>{Check(RenderControlV1.IsReady&&RenderControlV1.IsRenderingOwned);acquire++;};RenderControlV1.AfterRelease+=()=>{Check(!RenderControlV1.IsRenderingOwned);release++;};var panel=RenderControlV1.Acquire();var session=RenderControlV1.Acquire();panel.Dispose();Check(RenderControlV1.IsRenderingOwned&&release==0);var capture=RenderControlV1.Acquire();capture.Dispose();Check(RenderControlV1.IsRenderingOwned);session.Dispose();session.Dispose();Check(!RenderControlV1.IsRenderingOwned&&acquire==1&&release==1);}),
("all acquisition callbacks run and any failure aborts before snapshots",()=>{Ready();int callbacks=0,snapshots=0,releases=0;RenderControlV1.BeforeAcquire+=()=>{callbacks++;throw new Exception("participant failed");};RenderControlV1.BeforeAcquire+=()=>{Check(RenderControlV1.IsRenderingOwned);callbacks++;};RenderControlV1.AfterRelease+=()=>{Check(!RenderControlV1.IsRenderingOwned);releases++;};Throws(()=>{using var lease=RenderControlV1.Acquire();snapshots++;});Check(callbacks==2&&snapshots==0&&releases==1&&!RenderControlV1.IsRenderingOwned&&RenderControlV1.IsReady);}),
("acquire failure rolls back and later retry is supported",()=>{Ready();Action reject=()=>throw new Exception();RenderControlV1.BeforeAcquire+=reject;Throws(()=>RenderControlV1.Acquire());RenderControlV1.BeforeAcquire-=reject;using var lease=RenderControlV1.Acquire();Check(RenderControlV1.IsRenderingOwned);}),
("reentrant acquisition is rejected without leaked ownership",()=>{Ready();RenderControlV1.BeforeAcquire+=()=>RenderControlV1.Acquire();Throws(()=>RenderControlV1.Acquire());Check(!RenderControlV1.IsRenderingOwned);}),
("release callbacks cannot reacquire during transition",()=>{Ready();RenderControlV1.AfterRelease+=()=>RenderControlV1.Acquire();var lease=RenderControlV1.Acquire();Throws(lease.Dispose);Check(!RenderControlV1.IsRenderingOwned&&!RenderControlV1.IsReady);}),
("all release observers attempted and callback errors do not re-own settings",()=>{Ready();int calls=0;RenderControlV1.AfterRelease+=()=>{calls++;throw new Exception();};RenderControlV1.AfterRelease+=()=>{calls++;Check(!RenderControlV1.IsRenderingOwned);};var lease=RenderControlV1.Acquire();Throws(lease.Dispose);Check(calls==2&&!RenderControlV1.IsRenderingOwned&&!RenderControlV1.IsReady);lease.Dispose();}),
("shutdown readiness false before final restored release",()=>{Ready();using var lease=RenderControlV1.Acquire();int releases=0;RenderControlV1.AfterRelease+=()=>{Check(!RenderControlV1.IsReady&&!RenderControlV1.IsRenderingOwned);releases++;};RenderControlV1.BeginShutdown();Check(!RenderControlV1.IsReady&&RenderControlV1.IsRenderingOwned);Throws(()=>RenderControlV1.Acquire());lease.Dispose();Check(releases==1);}),
("restoration failure latches ownership and prevents release event",()=>{Ready();var lease=RenderControlV1.Acquire();int releases=0;RenderControlV1.AfterRelease+=()=>releases++;RenderControlV1.RestorationFailed();lease.Dispose();Check(!RenderControlV1.IsReady&&RenderControlV1.IsRenderingOwned&&releases==0);Throws(RenderControlV1.BeginHostInitialization);}),
("worker acquisition never runs callbacks or changes ownership",()=>{Ready();int callbacks=0;RenderControlV1.BeforeAcquire+=()=>callbacks++;Task.Run(()=>Throws(()=>RenderControlV1.Acquire())).GetAwaiter().GetResult();Check(callbacks==0&&!RenderControlV1.IsRenderingOwned);}),
("worker release rejection preserves releasable main-thread token",()=>{Ready();var lease=RenderControlV1.Acquire();Task.Run(()=>Throws(lease.Dispose)).GetAwaiter().GetResult();Check(RenderControlV1.IsRenderingOwned);lease.Dispose();Check(!RenderControlV1.IsRenderingOwned);}),
("normal shutdown permits same-thread host recreation",()=>{Ready();RenderControlV1.BeginShutdown();RenderControlV1.BeginHostInitialization();RenderControlV1.CompleteHostInitialization();using var lease=RenderControlV1.Acquire();Check(RenderControlV1.IsReady&&RenderControlV1.IsRenderingOwned);})};
int passed=0;foreach(var (name,run) in tests){Reset();try{run();Console.WriteLine("PASS "+name);passed++;}catch(Exception ex){Console.WriteLine("FAIL "+name+": "+ex);}}Console.WriteLine($"{passed}/{tests.Length} production coordination tests passed.");return passed==tests.Length?0:1;
static void Ready(){RenderControlV1.BeginHostInitialization();RenderControlV1.CompleteHostInitialization();}
static void Reset(){foreach(var field in typeof(RenderControlV1).GetFields(BindingFlags.NonPublic|BindingFlags.Static)){if(field.IsLiteral||field.IsInitOnly)continue;field.SetValue(null,field.FieldType.IsValueType?Activator.CreateInstance(field.FieldType):null);}}
static void Check(bool ok){if(!ok)throw new Exception("assertion failed");}
static void Throws(Action action){try{action();}catch{return;}throw new Exception("exception expected");}
